### ISSUE TITLE
mpremote mip install: file not found 

### ISSUE THREAD

**Issue by mchobby** [jimmo/micropython-mlx90640#1]
Hi Jimmo,
I'm trying to creates the package.json for one of my library stored there (only the oled-ssd1306).

https://github.com/mchobby/esp8266-upy/tree/master/oled-ssd1306

So I did creates the `package.json` file as it should be (I believe).

Unfortunately the `mpremote mip install github:mchobby/esp8266-upy/oled-ssd1306`

Does returns the following error 
```
Install github:mchobby/esp8266-upy/oled-ssd1306
Installing github:mchobby/esp8266-upy/oled-ssd1306/package.json to /lib
Package may be partially installed
mpremote: File not found: https://raw.githubusercontent.com/mchobby/esp8266-upy/HEAD/oled-ssd1306/ssd1306-v1.10.py
```
I do not understand why the HEAD file cannot be resolved.
What did I miss ?

**Comment by jimmo** [comment]
> I do not understand why the HEAD file cannot be resolved.

Because the path in package.json was wrong.

1. This is not the correct location to raise issues against `mip`.
2. It looks like you already solved the problem in https://github.com/mchobby/esp8266-upy/commit/ce400705bf5b10a624aff1cfb1430cac1a16ac2d (why didn't you close this issue?)
3. Do you actually need the collections.defaultdict dependency or did you copy that from the sample?

**Comment by mchobby** [comment]
Hi Jimmo,
1. You right. Sorry for disturbance.
2. For me, it was not yet solved... I did certainly forgot to push my update online (why it was still an issue for me, and why the issue was still open). 
3. Was copied from the sample and this was an error. It does "Installing: /lib/collections/defaultdict.mpy" so I do understand the behavior now!

The issue may anyway helps someone else using this example like I did.
Once again, sorry for annoyance.
Dominique
